swagger: "2.0"
info:
  title: "Reomir API Gateway"
  description: "API for the Reomir API, secured by Google ID Tokens."
  version: "v0.1.0"
schemes:
  - "https"
produces:
  - "application/json"

responses:
  CORSPreflightSuccess: # Name for your reusable response
    description: "CORS preflight successful. Standard CORS headers applied."
    headers:
      Access-Control-Allow-Origin:
        type: "string"
        default: "*" 
      Access-Control-Allow-Headers:
        type: "string"
        default: "Content-Type, Authorization"
      Access-Control-Max-Age:
        type: "integer"
        default: 3600

securityDefinitions:
  google_id_token_auth:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: ${GOOGLE_OAUTH_CLIENT_ID}

paths:
  /api/v1/agent: # Corrected: Removed trailing slash
    get:
      summary: "Performs an action in the reomir-agent"
      operationId: "performAgentAction"
      security:
        - google_id_token_auth: [] # Applies the 'google_id_token_auth' security to this path
      x-google-backend:
        address: "${CLOUDRUN_AGENT_URL}" # Replace with actual URL
      responses:
        "200":
          description: "Successful operation"
        "401":
          description: "Unauthorized - Token missing or invalid"
        "403":
          description: "Forbidden - Token valid but user not permitted"
  /api/v1/users/self: # Corrected: Removed trailing slash
    get:
      summary: "Retrieves user information"
      operationId: "getUserInfo"
      security:
        - google_id_token_auth: [] # Applies the 'google_id_token_auth' security to this path
      x-google-backend:
        address: "${CLOUDFUN_USER_URL}" # Replace with actual URL
      responses:
        "200":
          description: "Successful operation"
          headers: # <--- Recommended for CORS preflight
            Access-Control-Allow-Origin:
              type: "string"
              default: "*"
            Access-Control-Allow-Headers:
              type: "string"
              default: "Content-Type, Authorization"
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Max-Age:
              type: integer
    options: 
      summary: "CORS preflight for users endpoint"
      operationId: "optionsUsers"
      # security:
      #   - google_id_token_auth: []
      x-google-backend:
        address: "${CLOUDFUN_USER_URL}" # Point to the same backend
      responses:
        "200":
          description: "Successful CORS preflight"
          headers: # <--- Recommended for CORS preflight
            Access-Control-Allow-Origin:
              type: "string"
              default: "*"
            Access-Control-Allow-Headers:
              type: "string"
              default: "Content-Type, Authorization"
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Max-Age:
              type: integer