name: Terraform Lint & Validate 

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'terraform/**' # Trigger only if changes are within the 'terraform/' directory
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'terraform/**' 

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/ 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest" # Consider pinning to a specific version like "1.8.x"

      - name: Terraform Format Check
        id: fmt
        # Commands will now implicitly run from the 'terraform/' directory
        run: terraform fmt -check -recursive .
        # If terraform fmt -check outputs any diff, it exits with 1, failing the step.

      - name: Terraform Validate
        id: validate
        # Commands will now implicitly run from the 'terraform/' directory
        run: terraform validate