name: Deploy Cloud Functions

on:
  push:
    branches:
      - "master"
    paths:
      - 'functions/**' # Only trigger on changes in the functions directory
      - '.github/workflows/deploy_function.yml' # Also trigger if workflow changes

env:
  # --- GCP Cloud Functions Variables ---
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }} # Your GCP project ID
  GCP_REGION: europe-west1 # Cloud Function region
  SOURCE_DIRECTORY: ./functions # Directory containing Cloud Function source code

jobs:
  deploy_cloud_function:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: ["users", "session-mapper"] # Define which function subdirectories to process
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth (Workload Identity Federation)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-actions-pool/providers/github-provider
          service_account: github-actions-deployer@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      # New steps for running tests before deployment
      - name: Set up Python for tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Using Python 3.11 for tests

      - name: Install test dependencies
        # Sets the working directory for this specific step
        working-directory: ${{ env.SOURCE_DIRECTORY }}/${{ matrix.function }}
        run: |
          echo "Installing dependencies from $(pwd)/requirements.txt"
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found in ${{ env.SOURCE_DIRECTORY }}/${{ matrix.function }}."
            # Decide if this is a fatal error: exit 1
          fi
          echo "Installing pytest and werkzeug"
          pip install pytest werkzeug # Werkzeug needed for test environment

      - name: Run Python tests
        working-directory: ${{ env.SOURCE_DIRECTORY }}/${{ matrix.function }}
        run: |
          echo "Running tests in $(pwd)"
          pytest
      # End of new test steps

      - name: Deploy Cloud Function
        id: deploy
        uses: "google-github-actions/deploy-cloud-functions@v3"
        with:
          name: reomir-${{ matrix.function }}
          runtime: python313 # Deployment runtime
          region: ${{ env.GCP_REGION }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          source_dir: ${{ env.SOURCE_DIRECTORY }}/${{ matrix.function }}
          entry_point: handler
          # Example: Set build environment variables for the function if needed
          # build_environment_variables: 'KEY1=VALUE1,KEY2=VALUE2'
          # Example: Set service environment variables for the function if needed
          # environment_variables: 'CORS_ALLOWED_ORIGINS=*,FOO=bar'
